# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-07 19:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='itemDataPoint',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('itemID', models.IntegerField(default=0)),
                ('date', models.DateTimeField(default=datetime.datetime(2017, 7, 7, 19, 9, 58, 843007, tzinfo=utc))),
                ('price', models.IntegerField(default=0)),
            ],
        ),
    ]
