# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-07 19:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemdatapoint',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 7, 19, 10, 16, 876047, tzinfo=utc)),
        ),
    ]
