# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-05 23:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_tutorialmodel_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='componentmodel',
            name='order',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
