# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-09 21:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20170505_2339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='componentmodel',
            name='compID',
        ),
        migrations.AddField(
            model_name='componentmodel',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
