# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-11 21:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20170509_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorialmodel',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
