# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-18 20:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20170511_2126'),
    ]

    operations = [
        migrations.AddField(
            model_name='componentmodel',
            name='delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='componentmodel',
            name='componentType',
            field=models.CharField(choices=[('1', 'text'), ('2', 'image'), ('3', 'code')], max_length=1),
        ),
        migrations.AlterField(
            model_name='tutorialmodel',
            name='component',
            field=models.ManyToManyField(blank=True, null=True, to='app.componentModel'),
        ),
    ]
