# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-05 00:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_tagmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='itemDataPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemID', models.IntegerField()),
                ('date', models.DateField()),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='tagmodel',
            name='tutorials',
        ),
        migrations.RemoveField(
            model_name='tutorialmodel',
            name='component',
        ),
        migrations.DeleteModel(
            name='componentModel',
        ),
        migrations.DeleteModel(
            name='tagModel',
        ),
        migrations.DeleteModel(
            name='tutorialModel',
        ),
    ]
