# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-05 00:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20170705_0049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemdatapoint',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
