# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-07 17:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20170705_0050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemdatapoint',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
